env:
  browser: true
  es6: true
  node: true
  jest/globals: true
extends:
  - plugin:react/recommended
  - plugin:jest/recommended
  - plugin:jest-dom/recommended
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - import
  - jest
  - jest-dom
rules: {}
